### ISSUE TITLE
Menu of DPI remains greyed out at a pre-selected option after a different option is selected, the pre-selected option can not be re-selected

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#119]
I observed that _Standard_ was greyed out, as if selected – progress on https://github.com/trueos/trueos-core/issues/76 I guess – so I chose one of the other three options. 

The DPI changed but the menu did not. I found it impossible to regain the required DPI. 

Workaround: a different boot environment. 

Side note: https://discourse.trueos.org/t/solved-is-hidpi-support-available-in-lumina/96/8

**Comment by grahamperrin** [comment]
Reviewed with a fresh installation of `#55` to a 15" Apple MacBookPro11,2 with Retina display: 

- _High (4K, ~196 DPI)_ seems to pre-selected by the OS, not by the user
- after trying any lower resolution, that highest resolution can not be regained

– can not, because no matter which of the other three options is effective, that one pre-selected option remains greyed-out, non-selectable. 

Suggested milestone: stable.

**Comment by grahamperrin** [comment]
https://github.com/trueos/pcdm/blob/8e2b52d134dadb1ca800182be5c67564f0a1ee26/src-qt5/PCDM/src/pcdm-gui.cpp#L618 I guess

**Comment by q5sys** [comment]
The if statements in pcdm-gui.cpp are doing what they are supposed to do. I think the problem is a inheritance issue of the QString dpi in pcdm-backend.cpp.  In the mean time, I've overridden this so that they are always enabled all the time.
https://github.com/trueos/pcdm/commit/433a0d1348390aacda5dc72b1e94af4ca3e2e9e9
