### ISSUE TITLE
ZFS mount root error if attaching additional SATA disk

### ISSUE THREAD

**Issue by rmx-it** [trueos/trueos-core#135]
Hi,
on a quite new HP ZBook 17" G3 (XEON+NVidia Quadro) I'm using trueos-desktop because of its 
newer graphics support. [uname_ok.txt](https://github.com/trueos/trueos-core/files/566172/uname_ok.txt)

Up to now I had a built-in M.2 PCIE-AHCI (booting TrueOS) plus a 2.5" SATA SSD (booting Win)
[devl_ok.txt](https://github.com/trueos/trueos-core/files/566170/devl_ok.txt)

For a verbose dmesg see: 
[dmesg_ok.txt](https://github.com/trueos/trueos-core/files/566171/dmesg_ok.txt)

As soon as adding another 2.5" SATA disk (which is found as ada0) I can't boot any longer
because of the zfs mountroot is failing.
(The GPT boot loader is working fine though, zroot is found and the BE's also)

Could this be some timing race due to the amount of disk's (or maybe because the new disk is a
"slower" SATA Hard-disk instead of a SSD)

Currently I cant analyze this further because the graphical boot splash screen hides the main error
(see the other error message...)

Thanks in advance!

Greetings
----
mike

**Comment by pkgdemon** [comment]
I can confirm this is an issue for others as well.

**Comment by francisco1844** [comment]
Recently had a similar issue. If you go into "6 Options" on the initial screen you can then select "Verbose".

You will then see the progress text as it boots

**Comment by francisco1844** [comment]
Another option which was pointed out to me is to mute splash screen.

> $ grep -B 2 mute /boot/loader.conf.trueos 
> \# Display TrueOS splash image while booting the kernel
> boot_mute="NO"

Got info in  [discourse](https://discourse.trueos.org/t/install-gui-later/316/5) thread. I was having a [similar issue](https://discourse.trueos.org/t/how-to-do-clean-re-installs/311/7) which may be related to this problem.

For me the solution was to wipe out the new drives I was adding, but that is only viable for a new setup like I was doing. Spent 4 days troubleshooting until I was able to find how to enable verbose logs and then it was easier to see what the issue was.

**Comment by RodMyers** [comment]
Closed - resolved via

https://discourse.trueos.org/t/how-to-do-clean-re-installs/311/7

Dec 16, 2016 entry
