### ISSUE TITLE
gmtp - Android file transfer delays between LG G4 and TrueOS

### ISSUE THREAD

**Issue by danboid** [trueos/trueos-core#1426]
gmtp issues:

gmtp can be used to transfer files between a TrueOS/FreeBSD box and a modern Android device using a regular, data-capable micro USB cable. MTP (and hence gmtp) is the easiest, fastest and generally 'the best' method to transfer data for most Android users and gmtp is the only FreeBSD app I've got to work with my phone, an LG G4, but it is plagued by almost unbearable delays between actions that the user would be forgiven for thinking it really doesn't/ isn't going to work at all. It does....... eventually!

Hardware / software config is required to put these figures in context. These measurements were took from a System76 Gazelle Pro i7 laptop, 8GB RAM, 250GB Samsung SATA3 SSD running TrueOS with bang up-to-date packages but running MATE (1.12) instead of Lumina and running gmtp 1.3.10 installed from pkg. I connected an LG G4 running stock Android 6 plugged into a USB 2.0 port on my GPro. No other significant programs were being run simultaneously - no browsers etc - when I took these times.

gmtp actions/times:

Time taken to show device selection window after clicking gmtp Connect icon: ~2m 20s

Time taken to show storage card contents after picking MTP storage device. On the G4 I can pick either the phones internal memory or the microSD card as the device to browse: ~3m 10s

Time taken to delete one ~20MB .dng file off the MicroSD via gmtp, from clicking delete to gmtp being responsive again: ~3m 10s

Preeeetty sluggish! :(

Despite these many probs, browsing through the MTP filesystems, once they've finally shown themselves, is as fast as you could hope for and so is copying/downloading files to your drive - this works as fast I expect eg ~30MB/s so gmtp is actually usable but in a pretty painful way right now.

**Comment by danboid** [comment]
gmtp also disconnects instantly, unlike the mult-iminute connection delays.

**Comment by danboid** [comment]
I've had no luck whatsoever with this phone/laptop trying the FreeBSD / TrueOS command line MTP clients and tools, as documented over here:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=207718

**Comment by q5sys** [comment]
Have you made an attempt to test this on a FreeBSD 12.Current install?  I have an install on a disk lying around somewhere in my office, if I find it I can give it a try with my Blackberry Priv, but I fear that it wont be that helpful because Blackberry has changed so much in the OS, that it's not the same as regular Android systems.

**Comment by danboid** [comment]
No, I've not q5sys and I agree with what you say re the priv vs 'normal' (ha!) Android

**Comment by danboid** [comment]
I've created a support thread for this over on the gmtp sf.net forums:

https://sourceforge.net/p/gmtp/discussion/bugs/thread/de794613/

**Comment by danboid** [comment]
For anyone else wanting to try gmtp, note that you have to have:

fuse_load="YES"

Defined in /etc/rc.conf before gmtp will work.

I've not had any response on the gmtp forum yet.

**Comment by danboid** [comment]
Maybe I should've reported this to the FreeBSD gmtp port maintainer instead?

**Comment by danboid** [comment]
The gmtp author has replied to me over on the sf.net forum but sf.net isn't letting me login, even after resetting my password 3 times so I'm replying here instead.

After enabling the alternate connection method option under prefs, there is now no delay when I click on the Connect icon in bringing up the device selection window but that is the only difference - all the other delays remain.

I disabled fusefs but gmtp is still working so maybe I had to enable the alternate connection mode? My phone is obviously happier using the alternate mode.

Here's the debug info you requested:

https://gist.github.com/danboid/a13fc669e697d64482ac4a96a676a4a7

https://gist.github.com/danboid/530f631390231a657e8202e22c02866c

Thanks!

**Comment by dkartaschew** [comment]
Cross posting from the gmtp.sf.net

Hi Daniel,

Thanks for that, from what's provided, the device is responding correctly (eg, there are no timeouts on commands issued to the device, which is a common cause for lag).

Unfortunately, the output doesn't include timings/timestamps between each call. Was using mtp-detect slow as well?

There are two options:
1. run 
> $ export LIBMTP_DEBUG=13
> $ gmtp

So I can check what calls are being made, at each layer.

or 2. run
> $ truss -d -D -S -o gmtp.out gmtp

to use the FreeBSD truss utility to follow the program flow. (Note: I don't have a FreeBSD box/VM handy to check if "-d -D" can both be used at the same time).

The only operation I need to do its:
1. connect to the device, selecting one of the storage devices.
2. browse to a single folder on the device.
3. disconnect.

Hopefully from there we can determine where the fault is.

Additionally, as most applicatons use libmtp underneath (like gmtp) and if the issue is in libmtp, there is Android-File-Transfer ( https://github.com/whoozle/android-file-transfer-linux ) which doesn't use libmtp. You could this application a try to see if it solves your issues.

Kind Regards, Darran

**Comment by danboid** [comment]
Hi Darren

Thanks for your quick replies!

I've attached the output from libmtp debug level 13 - there is rather a lot produced after selecting the device to open!

[trueos-debug.zip](https://github.com/trueos/trueos-core/files/1031582/trueos-debug.zip)

It's zipped xzip, silly github uploading policy!

Is Android File Transfer known to work under FreeBSD? They only mention Linux and OSX on its site?

Thanks

**Comment by dkartaschew** [comment]
Hi Daniel,

Can I please get the output from truss?  

Unfortunately, the log file you've provided doesn't provide the timestamps needed to determine where the slow downs are.

Darran

**Comment by dkartaschew** [comment]
AFT can use the libusb 0.15.x API (which FreeBSD provides) so I don't see why it won't work.

**Comment by danboid** [comment]
Hi Darran

truss accepted both -d and -D:

[trueos-gmtp-truss.zip](https://github.com/trueos/trueos-core/files/1033470/trueos-gmtp-truss.zip)

Thanks

**Comment by dkartaschew** [comment]
Hi Daniel, 
Thanks for the log file.
Basically, your device is taking a very long time to respond to commands. This could be due to (I suspect) a few different things (some or all may apply):
1. The MTP service your phone is using is broken in some manner.
2. The underlying storage on your phone is causing the MTP service to timeout in some manner, resulting in poor performance of the MTP service on the device.
3. There is some sort of incompatibility between the USB library, USB driver implementation in the FreeBSD kernel, the USB controller in your PC and the USB controller on the phone.
4. libmtp (which is what gmtp uses to talk to devices) is doing something that your phone doesn't like, or not doing something that your phone is expecting. (I doubt this is the case, based in the libmtp debug output you've provided). 

If you look in the log file, at around lines 4800-5000, you'll see the libmtp library sending a few commands to the device, and then a whole stack of ERR#35 'Resource temporarily unavailable' and ERR#16 'Device busy' errors on the write and similar for the corresponding read for results from the MTP command being sent. This repeated throughout the log file essentially for every read/write to/from the device. (One such set runs from line ~5900 for the write a command to the device, until line ~64000 for when something is returned from the device - approximately 40 seconds).

This is telling me that, the most likely cause is either points 1, 2 or 3 as listed above. 

At this point there is little I can assist with further, other than I recommend that you try to contact the maintainers of the USB driver and libusb implementation on TrueOS/FreeBSD, pointing them towards this bug report and log files. They might be able to assist further or may give you some additional things to test with.

Kind Regards,
Darran

**Comment by danboid** [comment]
Hi Darren

Thanks for looking into this for me.

I don't think it is #1 because my phone doesn't suffer any such delays under Linux or Windows, or at least no more than a few seconds when you first access it. It sounds to me as if it must be a FreeBSD kernel or FreeBSD libusb problem.

Turns out android-file-transfer is in the TrueOS repos but that seems unhappy with libusb too as all I get out of it is:

error: libusb_bulk_transfer(_handle, ep->GetAddress(), const_cast<u8 *>(data.data()), data.size(), &tr, timeout): LIBUSB_ERROR_TIMEOUT
