### ISSUE TITLE
dd TrueOS.img: GEOM: da0: the secondary GPT header is not the latest LBA

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/trueos-core#1435]
Intel NUCs: DN2820FYKH & 5PPYH.

MD5 sum of TrueOS-2017-06-01-x64-USB.img is OK.

(on root) dd if=TrueOS-2017-06-01-x64-USB.img of=/dev/da0 bs=1m
GEOM:da0:the secondary GPT header is not the latest LBA
(on root) gpart recover da0
da0 recovered

This problem is observed in all previous versions of TrueOS and FreeBSD.

![lba](https://cloud.githubusercontent.com/assets/20837310/26750148/312a60ce-4835-11e7-8f42-c7fe30dc5127.png)

**Comment by darkfiberiru** [comment]
Dmitry,

When a USB image is created it's a fixed size and knows nothing about the device it will end up on. It's just a series of bytes be copied bit by bit using dd or a similiar tool to your usb stick. 

GPT the partition scheme here expects two headers with partition tables. One at the front of the disk and one at the very end for redundancy. Since the usb stick you are copying to is bigger then the image the gpt header at the end of the image gets put some in the middle of your usb stick. The OS expects to see it at the last LBA (Logical Block Addressing) meaning the end of your usb stick.

As such the host thinks your usb stick is now "damaged" as it can't find the secondary header. This header exists on the usb stick just not where it is looking. You could also have a different gpt secondary header at the end of the usb stick which can cause some different fun behavior.

This is all as is expected and shouldn't affect anything. 

The recover command will take the Main gpt header and copy it to the end of the usb stick. Clearing up these and some related error messages. But not everyone burning usb sticks is doing it from a freebsd box with access to gpart and there should be no functional difference of the usb stick.

Does this all make sense?

**Comment by DmitryPostolov** [comment]
**darkfiberiru**,

Thanks! Problem closed.
