### ISSUE TITLE
PCDM: Change Video Driver issues

### ISSUE THREAD

**Issue by danboid** [trueos/trueos-core#1457]
I just borked my xorg config by using the Change Video Driver within the PCDM menu.

I was having slight display issues when using the modesetting driver so I wanted to test the Intel driver (is that a valid option?) instead because I am using an Intel Haswell HD4600 GPU.

When I picked ‘Change video driver’ from the PCDM menu in the bottom right of the PCDM login screen and it instantly broke my display (it became misaligned / off-centre) before showing the ‘Pick your driver’ window. I picked ‘Intel’ and it seemed to apply some changes after I OK’d it as the screen flickered but I was then waiting on it to revert to the previous driver but it never did so I had to kill my box with a hard power off. When I rebooted, X was using the VESA driver instead of modesetting, VESA doesn’t work properly on my laptop at all - the screen isn’t centred properly and the full desktop isn’t visible.

After I rebooted, my X config was borked so I had to revert to an older, pre UNSTABLE update BE to get working X again (without adjusting xorg.conf manually).

I believe there are at least two very closely related issues here so I'm documenting them in this one issue:

1 - The PCDM Change Video Driver function/helper makes it sound as if it will be reverting to the current video driver after testing your new selection but that never happened for me. Should it?

(As a side note, is there any logic in place to prevent people who have only an Intel GPU from accidentally testing the Nvidia or AMD specific drivers and vice versa?)

2 - It would appear that the Change Video Driver adjusted my xorg.conf file before I had picked a working driver. Because of the first issue (PCDM not reverting to the previous driver after 30 seconds or so) I had to nuke my machine as I didn't have sshd running so I knew of no clean way to back out.

**Comment by danboid** [comment]
I have since checked my UNSTABLE BE xorg.conf after having attempted to use Change Video Driver. It had changed it to use the "vesa" instead of the "modesetting" driver. I tried deleting this xorg.conf and noticed TrueOS created a new xorg.conf in its place on the next boot that defaulted to vesa too.

Manually editing xorg.conf to set the video driver to modesetting has mostly fixed my UNSTABLE video.

**Comment by danboid** [comment]
I had chosen 'Intel' from the Change Video Driver menu but it rewrote my xorg.conf to use the vesa driver. That would seem to be the main bug here.

Additionally, what I've experienced today has shown me that the modesetting driver is a much better default / fallback video driver than vesa, at least for intel users.

**Comment by beanpole135** [comment]
I just finished the conversion of the pc-xgui utility to always use a "test.xorg.conf" file and only replace the "real" xorg.conf when the user accepts the changed driver[1].

By the same token, treating "modesetting" as a fallback driver (which it is not) is quite dangerous because loading the intel module can really bork particular types of systems. VESA and SCFB are really the only two fallback drivers, and are used for Legacy/UEFI booting respectively. The SCFB driver is actually quite a nice fallback with native-resolution detection/support (VESA is really, really old), but you need to be booting with UEFI capabilities for it to work (which most modern computers already can do).

[1] https://github.com/trueos/trueos-utils-qt5/commit/c21aa06130d37037b7fa6d21ef88e7974c8d7507
