### ISSUE TITLE
add avahi-daemon and gutenprint by default

### ISSUE THREAD

**Issue by nielsk** [trueos/trueos-core#1465]
I had to add a printer today. Iirc foomatic-db was already installed but not gutenprint (or was it the other way around?). And therefore I needed the other one to install it to get the driver. That was not documented properly in the TrueOS-handbook and in the research part, it led me to a site that didn't know my printer. Only because of earlier experimentations with this printer and FBSD I remembered that this was there. Adding it to the default install would broaden the available printer drivers and make it more usable to the non-nerd. 
In addition adding avahi-daemon to default would be great, so that zeroconf works. I couldn't get it to work with my printer in the end but it already helped. I have the feeling that there was just a piece of the puzzle still missing that zeroconf could have worked. 
Please improve that experience. The image is already sooo huge (2.x GBye? A Fedora-image that installs this printer in a minute automagically more or less comes in only 1.5GB) that it shouldn't matter that much space-wise. "Only" maybe engineering-wise in getting zeroconf to work.

**Comment by beanpole135** [comment]
The `print/gutenprint-cups` and `print/cups-pdf` packages are already pre-installed on users systems. The `print/foomatic-db` package was removed from the install a while back due to a bad bug which would render all printing through cups impossible. If this bug has been resolved however, we could always re-enable that package for the default installation as needed.

By the same token, the `net/avahi-app` package (CLI/library interface to mDNS browsing) is already  pre-installed on TrueOS systems as a required dependency of the `print/cups-pdf` package.

**Comment by beanpole135** [comment]
I just did a bit more digging, and it looks like the `print/foomatic-db` was already re-added to the install media and/or system. 
It is a required dependency of the `trueos-desktop` meta-package.

Since all the requested packages are already pre-installed on the system, I will go ahead and close this issue.
