### ISSUE TITLE
Unstable update - Aug 5/6 - nVidia fails

### ISSUE THREAD

**Issue by VulcanRidr** [trueos/trueos-core#1467]
I woke up this morning to the flashing yellow sysadm-client icon in the tray. After the update completed, the system rebooted. I got no X, and the nvidia.ko and nvidia-modeset.ko did not load. dmesg showed 

KLD nvidia-modeset.ko: depends on kernel - not available or version mismatch
linker_load_file: /boot/modules/nvidia-modeset.ko - unsupported file type
KLD nvidia.ko: depends on kernel - not available or version mismatch
linker_load_file: /boot/modules/nvidia.ko - unsupported file type

I have currently rebooted into the previous BE until I can work out what the issue is.

**Comment by darkfiberiru** [comment]
Logs from the failed attempt would be helpful. This maybe be caused by some of the work going on to improve updates across abi changes of any magnitude. 

You should be able to retrieve those logs by:

beadm mount UPGRADED-BE-NAME /mnt/failed-upgrade
tar -xf ~/failed-upgrade.log.tar /mnt/failed-upgrade/usr/local/log/pc-updatemanager
beadm umount UPGRADED-BE-NAME

You can add the file here. The main file to be concerned about is upgrade.log. I am curious about the other files even if empty though.

**Comment by VulcanRidr** [comment]
Please find the attached zip file. github, for whatever reason, said it could not process the tar.

[failed-upgrade.zip](https://github.com/trueos/trueos-core/files/1204048/failed-upgrade.zip)

**Comment by beanpole135** [comment]
There appears to have been a slight issue with the CDN over this last weekend which resulted in the wrong packages being seen/used during the upgrade routine. This has already been fixed.

Please revert to the previous/good boot environment and you should be able to do updates properly now.

**Comment by RodMyers** [comment]
Just rebooted into BE, update (firefox/thunderbird) still failing
