### ISSUE TITLE
pc-mixer: Tricky to open mixer from tray icon menu

### ISSUE THREAD

**Issue by danboid** [trueos/trueos-core#1476]
At the bottom of the pc-mixer tray icon dropdown menu is a link to the Mixer but it only opens reliably if you click on the small wrench icon. If you click on the word 'Mixer' or the whitespace to the right it doesn't open the mixer. 

Ideally you should be able to click anywhere within the full horizontal width of the menu that is aligned vertically with the wrench icon and the word 'Mixer' to open the mixer.

**Comment by Mrt134** [comment]
Hmm, I'm unable to reproduce - I can reliably open the Mixer window by clicking anywhere in the entry: icon, text, or whitespace. I'm running latest UNSTABLE with Lumina Theme engine enabled, is this the same as you?

**Comment by danboid** [comment]
How / where to enable/disable lumina theme engine?

**Comment by Mrt134** [comment]
Just got an update - this issue was [identified and fixed](https://github.com/trueos/pc-mixer/commit/51126a6d1faa5fe17f25d48c32e7bcf338a0afce) a little while ago. It is confirmed no longer present in the latest UNSTABLE build.

Theming is unrelated to this issue (wrong instinct on my part, sorry), but we are testing an experimental theme engine that is available in the latest UNSTABLE build. After updating, it is available from `Applications -> Settings -> Lumina Theme Engine`. You can adjust the application theme being used with `Preferences -> All Desktop Settings -> Theme -> Application Themes`.

Thanks for the report!
