### ISSUE TITLE
WIFI connection lost after plugging in LAN cable

### ISSUE THREAD

**Issue by q-pa** [trueos/trueos-core#1485]
I am on latest UNSTABLE TrueOS-Desktop-201707111911.

To reproduce:
1. Connect to network via WIFI
2. Plug in LAN cable 
3. un-plug LAN cable 

Result:
WIFI seems to be still connected but internet connection is lost.
Re-starting network results in infinite search for a network.
Only rebooting turns back on WIFI connection.

**Comment by beanpole135** [comment]
Update: While the updates were downloading, I unplugged my LAN cable (leaving the adapter still attached) and this reproduced the issue you mentioned. I am doing some tests on it now to see how to bring the wifi adapter back up....

**Comment by q5sys** [comment]
Although it might be anomalous due to networking being weird on my system, but when I connect with wifi and then plug in a LAN cable, wifi remains the network of choice.  All applications will use wifi instead of the active ethernet.  I can remove the ethernet cable without issue or loss of connectivity since it wasn't being used. 
Do we have a method of dictating networking priority?

**Comment by q-pa** [comment]
I'm on the latest UNSTABLE release and cannot reproduce this issue anymore.
