### ISSUE TITLE
OpenRC net-online for TrueOS

### ISSUE THREAD

**Issue by maurizio-emmex** [trueos/trueos-core#1494]
I have converted the script  [net-online](https://github.com/OpenRC/openrc/blob/master/init.d/net-online.in) written for Linux.
```
#!/sbin/openrc-run
# Copyright (c) 2015 The OpenRC Authors.
# See the Authors file at the top-level directory of this distribution and
# https://github.com/OpenRC/openrc/blob/master/AUTHORS
#
# This file is part of OpenRC. It is subject to the license terms in
# the LICENSE file found in the top-level directory of this
# distribution and at https://github.com/OpenRC/openrc/blob/master/LICENSE
# This file may not be copied, modified, propagated, or distributed
# except according to the terms contained in the LICENSE file.

# Original source: https://github.com/OpenRC/openrc/blob/master/init.d/net-online.in

description="Delays until the network is online or a specific timeout"

depend()
{
	after modules
	provide network-online
}

start ()
{
	local rc infinite dev found

	ebegin "Checking to see if the network is online"
	rc=0
	interfaces=${interfaces:-$(ifconfig -nl "ether")}
	timeout=${timeout:-120}
	[ "$timeout" -eq 0 ] && infinite=true || infinite=false
	found=false
	while $infinite || [ "$timeout" -gt 0 ]; do
		for dev in ${interfaces}; do
			if ifconfig "$dev" | grep "status:" | grep -E "active|associated" > /dev/null 2>&1; then
				ifconfig "$dev" | grep "^[[:blank:]]inet " | grep " broadcast "  > /dev/null 2>&1 && { found=true; break; }
			fi
		done
		[ $found = true ] && break
		sleep 1
		: $((timeout -= 1))
	done
	! $infinite && [ $timeout -eq 0 ] && rc=1
	include_ping_test=${include_ping_test:-${ping_default_gateway}}
	if [ -n "${ping_default_gateway}" ]; then
		ewarn "ping_default_gateway is deprecated, please use include_ping_test"
	fi
	if [ $rc -eq 0 ] && yesno "${include_ping_test:-no}"; then
		ping_test_host="${ping_test_host:-google.com}"
		if [ -n "$ping_test_host" ]; then
			ping -c 1 "$ping_test_host" > /dev/null 2>&1
			rc=$?
		fi
	fi
	eend $rc "The network is offline"
}
``` 
The configuration file is the same as in Linux: [net-online](https://github.com/OpenRC/openrc/blob/master/conf.d/net-online)

**Comment by q5sys** [comment]
Thanks for sending that in!  Sorry it took us a while to respond.  I've assigned Zach to the ticket, he's our Open-RC wizard, so I'm sure he'll appreciate the assist.

**Comment by beanpole135** [comment]
Done!
https://github.com/trueos/freebsd/commit/9f6231040b691e70ff3f7fb70e54c48e493b27f4

Thanks for sending that in!

**Comment by rostwald** [comment]
It seems an interface status of "[active|associated] and a set "broadcast" address doesn't work reliably for DHCP interfaces and causes ypbind to fail at startup, which leads to PCDM and login on consoles to hang several minutes. ypbind then has to be restarted manually in order to work.

I discovered this issue only a few days ago, after investigating how OpenRC on linux solves the problem of starting network-dependent services and finding the concept of the "net-online" service.
I've used a net-online script which tries to send a broadcast, which only succeeds if the link-layer on any interface is up and working. 
This has proven to be reliable, at least for our use case with NIS and NFS, which the script above unfortunately wasn't.

I've merged the broadcast-approach to the recently added script and created a pull request:
https://github.com/trueos/freebsd/pull/10
The ypbind service also needs to have the net-online service set a dependency:
https://github.com/trueos/freebsd/pull/11
