### ISSUE TITLE
Cannot join Telegram group in QuipZilla

### ISSUE THREAD

**Issue by khanzf** [trueos/trueos-core#1534]
The default web browser is QuipZilla. When I enter the URL in the Freenode IRC channel (t.me/TrueOSCommunity), I am redirected to a link "tg://resolve?domain=TrueOSCommunity". QuipZilla cannot handle tg:// links by default and fails.

In order to join, I had to use my phone. This may be a problem for new users.

**Comment by beanpole135** [comment]
That sounds like you are using the old webkit-based version of QupZilla instead of the WebEngine-based version (2.1.2 ?).
The newer version is used on the UNSTABLE branch of TrueOS, but I don't recall if STABLE has that version by default yet. In either case, it looks like this issue *is* resolved by updating the system/browser.
