### ISSUE TITLE
trueOS graphical installer uses wrong resolution in VMware Fusion 8.5.2

### ISSUE THREAD

**Issue by cro** [trueos/trueos-core#167]
The screen is clipped at the bottom.  See screenshot below.  The clipping continues after the installation is complete.

![screen shot 2016-11-23 at 9 48 55 am](https://cloud.githubusercontent.com/assets/83323/20571021/1a66d872-b163-11e6-9d0e-311b5f6d2f3d.png)

**Comment by pkgdemon** [comment]
As far as we know the resolution has to be hardcoded in xorg.conf.  This ticket has some helpful info to get the mouse working better as well.  

https://github.com/trueos/trueos-core/issues/58

We do not have vmware fusion to test this so this is difficult to fix.  If you can assemble, and confirm a working xorg.conf with a higher resolution 1024x768 would likely do it I could patch our default xorg conf for VMware installs.  I closed the last ticket only because I could never get a response back.  Hard to fix what we dont have.  :(  I will keep this open for a while if you can try the configs from the ticket.  Let me know if you need help.

**Comment by cro** [comment]
Let me see what I can do.

**Comment by pkgdemon** [comment]
We just need a working xorg.conf to produce a fix.  If you can come up with one let us know, and we can ship it.
