### ISSUE TITLE
Lumina hanging at Finalizing step

### ISSUE THREAD

**Issue by orangecms** [trueos/trueos-core#168]
Prerequisites: I just installed the latest release of TrueOS (TrueOS-Desktop-2016-10-28-x64-USB.img) on a new laptop yesterday. I had to set the bootloader to GRUB because I am using GELI and switch off ACPI for video in the kernel params because otherwise the system wouldn't boot.

Issue: When I log into Lumina from PCDM, the small info box shows a few messages, but doens't get past "Finalizing". I can still use the mouse then.

More info: When I go to another TTY, have `exec start-lumina-desktop` in `.xinitrc` and run `startx -- :2`, Xorg crashes and shows an error about a missing `.serverauth.dddd` file. I can, however, launch another WM, in my case i3. I also noticed that some files in my user's home directory were owned by root, so I changed that to my user. That didn't fix the issue either, but helped with errors raised from other applications.

**Comment by beanpole135** [comment]
That is really strange...
The "Finalizing" step is basically just launching the external processes setup within your "autostart" directories and playing the audio login chime (if enabled).
If you have a bunch of permissions errors in your home directory, then try moving the `~/.config/lumina-desktop` directory out of the way (to "lumina-desktop-old" or something). Similarly, check that the ~/.config directory is not root permissioned so that applications (such as Lumina) can create their settings in there as needed.

**Comment by pkgdemon** [comment]
I was seeing this issue as well.  It has been resolved for me as of 12-15-16, and 12-27-16 images.  Please let us know if it is still a problem so we can re-open.
