### ISSUE TITLE
New image?

### ISSUE THREAD

**Issue by saghm** [trueos/trueos-core#180]
Hi! I was wondering if there were any plans to release another image sometime soon. It looks like there's been a lot of progress recently (I'm particularly excited for OpenRC), and I'd love to be able to try it out. Alternately, if there's any documentation for manually compiling and making the image, I don't mind having to do it myself.

(Apologies if this isn't the correct repo to open this issue on; this is my first time looking at the TrueOS Github, so I'm not entirely sure if this belongs somewhere else)

**Comment by jungle-boogie** [comment]
I'm not speaking on behalf of this project, but I happen to know the group is  actively testing the newest and latest changes.
you can chat with the team here: https://gitter.im/trueos/Lobby

Right now I'm on the late October image and hopefully unstable will be tagged stable early next week.
After you update, you could change from stable to unstable, but I recommend doing that only if you're extremely adventurous. Otherwise, stable releases should happen every couple weeks.

**Comment by kmoore134** [comment]
Normally we would have pushed something public by now, but the OpenRC conversion has taken a while longer than expected to work out all the⁣ kinks. I should have a more solid image ready next week though. 

Thanks for being patient!

**Comment by saghm** [comment]
Awesome, thanks so much for letting me know! I definitely understand that this is a pretty big undertaking, so I appreciate that you all are taking the time to do it right.

Keep up the good work!
