### ISSUE TITLE
bhyve TrueOS as guest - login_tty /dev/ttyu0: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by prsi** [trueos/trueos-core#182]
Hi All,
I have installed TrueOS-Server-2016-10-28-x64 and configured bhyve to run the same TrueOS as a guest.
During the guest installation, I get the following errors. I even tried with "[T]ext Install/Console..... On" but the problema persist.

trueos getty[855]: getty: unknown gettytab entry '3wire'
trueos getty[855]: getty: unknown gettytab entry '3wire'
trueos getty[855]: tcsetattr /dev/ttyu0: Operation not supported
trueos init: getty repeating too quickly on port /dev/ttyu0, sleeping 30 secs
trueos getty[856]: getty: unknown gettytab entry '3wire'
trueos getty[1171]: login_tty /dev/ttyu0: Inappropriate ioctl for device

Any clues?

**Comment by pkgdemon** [comment]
You can get around this by using bhyve gop (graphics output protocol mode) which you would have to have for TrueOS desktop anyway to use the installer either way.  In regards to the default serial output mode I would speculate the issue is with out default /etc/ttys in comparison to FreeBSD.  See the following article below specifically the line that starts with fbuf to use bhyve graphics mode.

https://wiki.freebsd.org/bhyve/UEFI
