### ISSUE TITLE
The 'linux_enable' boolean should be set in no more than one file

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#197]
Related: https://github.com/trueos/freebsd/commit/0af2dbd9b11c7ac54baef4b3bcd762f85bd3a658

Now: 

```
$ date ; uname -v
Sun 11 Dec 2016 11:46:54 GMT
FreeBSD 12.0-CURRENT #57 6196e09(drm-next-4.7): Sat Dec 10 17:31:03 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
$ sudo grep -R -i linux_enable= /etc/
/etc/rc.conf.trueos:linux_enable="YES"
/etc/rc.conf:linux_enable="YES"
$ 
```

**Comment by pkgdemon** [comment]
@grahamperrin Good catch.  We no longer install /etc/rc.conf.trueos on fresh installs.  It's just something being left around after upgrades.  Fortunately it is completely ignored by openrc.  

@kmoore134 Can we add something to remove /etc/rc.conf.trueos in your one time migrate script, or would pc-updatemanager be a better place since that is where the openrc /etc overlays get installed?
