### ISSUE TITLE
With update to OpenRC, previous boot environment always upgrades

### ISSUE THREAD

**Issue by jmdavis** [trueos/trueos-core#226]
I just tried updating to my TrueOS install today (2016-12-17) to the latest from the pre-OpenRC version of TrueOS, and when I went back to the old boot environment, I found that every time I reboot from it, it creates a new boot environment and updates into it, instead of just doing it the first time I reboot.

[pc-updatemanager.log](https://drive.google.com/open?id=0B-tyih3w2oDZOV9MU2RCd1NJbDQ)

**Comment by grahamperrin** [comment]
Whenever you boot the old environment, do you _then also_ use the Update Manager pane of SysAdm to prefer no automation? 

Does this file exist? 

`/tmp/.rebootRequired`

If I understand correctly: 

- for users of Lumina it should be possible to avoid the route to the second stage of the update routine by removing that file
- if removal does not have the desired effect for users of Lumina, that's a bug, a known issue
- the bug was recently fixed but that fix may be not effective whenever you boot the old environment

– and (sorry) I don't know whether the fix, relatively late, was effective for the first push of OpenRC-enabled TrueOS to the stable repository. @baitisj may know. 

HTH

**Comment by jmdavis** [comment]
One of the first things I did after installing TrueOS was turn off automatic updates. I just use `pc-updatemanager pkgcheck` and `pc-updatemanager pkgupdate` without doing anything with the GUI. And I don't know why Lumina would matter at all, since updates shouldn't have anything to do with the DE. I am using KDE though, and I rebooted from PCDM (or whatever the login manager is called). So, if for some weird reason, in order for the updates to work correctly, you had to be using Lumina or the GUI to do the updates, then that could be part of the problem. I would hope that that wouldn't be the case though.

`/tmp/.rebootRequired` was there, and removing it did not fix the problem. However, when I removed everything in `/tmp` and `/var/tmp`, the problem did go away. And based on the files in there, it looked like those directories were not being cleared on reboot like they should be. So, maybe the update process assumed that they would be and didn't remove whatever file(s) mattered.

So, if the OpenRC version of things properly cleans out `/tmp` and `/var/tmp`, then this problem probably won't persist with updates in the future, though I would have thought that the update stuff would clean up after itself.

**Comment by baitisj** [comment]
Also, there was (is) a bug in non-openRC that results in constitutive activity of auto-update; in other words, the option to disable auto-update doesn't work properly.
This was fixed and my understanding is that it will be pushed out with the *upcoming* release of STABLE.

**Comment by kmoore134** [comment]
Correct, the latest packages I believe correct this. If you see it again though, please re-open.
