### ISSUE TITLE
/etc/rc: $ is not set properly - see rc.conf(5)

### ISSUE THREAD

**Issue by tiomadrid** [trueos/trueos-core#240]
AppCafe showed no apps and UpdateManager no upgrades. Therefore, after pkg update -f and pkg upgrade, TrueOS fails to boot. A lot of these error messages show /etc/rc: $ is not set properly - see rc.conf(5) before the FreeBSD login prompt. After login to FreeBSD, startx fails.

**Comment by tiomadrid** [comment]
System is FreeBSD 12.0-CURRENT. Booting any other boot environment shows the TrueOS login which after giving credentials briefly disappears in a black screen and reappears,

**Comment by pkgdemon** [comment]
When using the other boot environment it may be worth trying another window manager such as fluxbox at the PCDM screen.  If that works maybe lumina settings can be removed, and recreated.  Or whichever DE you are trying to log into.  Assuming lumina ```rm -rf ~/.config/lumina-desktop``` should effectively reset to defaults.

**Comment by pkgdemon** [comment]
Regarding the failed update the other option would be to restore to a working BE.  Then log into fluxbox, or console using ```CONTROL + ALT + F1```.  Then run: 

```sudo pkg clean -a```
```sudo pc-updatemanager pkgcheck```
```sudo pc-updatemanager pkgupdate```

The ```pc-updatemanager pkgcheck``` will just do ```pkg update -f``` for you as well as fetch required distirubtion updates for /etc.  Similarly ```pkg-upgrade``` will not create a boot environment, or touch the files in /etc that need upgraded.  Therefore it is best to use pc-updatemanager to call those tools so it does the right thing we need in order to have a proper upgrade.  After updating also never use ```reboot``` but ```shutdown -r now``` as ```reboot``` will bypass the install stage.

**Comment by tiomadrid** [comment]
Loaded the initial TrueOS BE and the first one thereafter and tried fluxbox. All that happened looked like refreshing PCDM.

# pkg clean -a
gives a lot of these  pkg-static unlinc(/usr/local/temp) : Read-only file system
Deleting files 100%
3368 packages could not be deleted

# pc-updatemanager pkgcheck
gives among others
Boot-strapping updater...FAILED Fetch
Read-only file system error : Error 74: /usr/local/sbin/pkg-static update

# pc-updatemanager pkgupdate
gives among others
Boot-strapping updater...FAILED Fetch
Read-only file system
override rw-r--r-- root/wheel uarch for /usr/local/etc/pkg/repos/trueos.conf?   =>Should I hit y?

**Comment by kmoore134** [comment]
The overarching issue of rc $ not set properly should be fixed in next package set.
