### ISSUE TITLE
nvidia driver should be built with linux compat support

### ISSUE THREAD

**Issue by gallatin** [trueos/trueos-core#245]
When trying to run a linux GLX binary (like glxinfo) & pointing it at matching Linux Nvidia GL and GLX libs,  it fails after issuing an ioctl to /dev/nvidiactl:

 27698 glxinfo  RET   linux_waitpid 27717/0x6c45
 27698 glxinfo  CALL  linux_open(0xffffb6c8,0x8002,0)
 27698 glxinfo  NAMI  "/compat/linux/dev/nvidiactl"
 27698 glxinfo  NAMI  "/dev/nvidiactl"
 27698 glxinfo  RET   linux_open 4
 27698 glxinfo  CALL  linux_fcntl64(0x4,0x2,0x1)
 27698 glxinfo  RET   linux_fcntl64 0
 27698 glxinfo  CALL  linux_ioctl(0x4,0xc04846d2,0xffffb748)
 27698 glxinfo  RET   linux_ioctl -1 errno -22 Invalid argumet

I *think* this is happening because the TrueOS nvidia.ko kernel module is built without the NV_SUPPORT_LINUX_COMPAT hash define enabled.

I'm deducing this because:

1) failed ioctl
2) nm on the nvidia.ko binary does not show a linux_ioctl_nvidia in the text
3) I don't see a module dependency on the linux module

**Comment by pkgdemon** [comment]
We had to turn it off Linux support for several reasons.  It's still broken in FreeBSD, and several issues remain open.  In additional installing things like google earth will remove NVidia-driver until fixed in FreeBSD ports.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=206711
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203447
