### ISSUE TITLE
xrdb requires a working C preprocessor (cpp) to compile it's resources

### ISSUE THREAD

**Issue by NorwegianRockCat** [trueos/trueos-core#250]
If you have a set of X resources (or X defaults) in a file, they won't be read until you install a compiler.

## Steps to reproduce

1. Create an .Xresources file with some custom settings (I believe a new user has this happen already).
1. Start X (or login via PCDM)
1. Check to see if these settings are actually there by running:
xrdb -query
1. If the default compiler is not installed, it will say: 
ERROR: Please install llvm39
1. Installing llvm39 and restarting X makes things work again.

I understand the desire to not install a compiler, but maybe some sort of working preprocessor would  be good for running X.

**Comment by beanpole135** [comment]
Ok, we just talked about this internally and decided on the following:
1) Update the xrdb port to add a runtime dependency on a compiler (the real source of the issue - unlisted runtime dependency within the port).
2) Remove xrdb as a dependency of the trueos-base and trueos-desktop packages. TrueOS does not actually use xrdb, and that will keep the default installs smaller and such.

This should clean things up considerably, because xrdb is getting used less and less as time goes on (TrueOS does not use it at all out-of-box), but it is still available for people to install/use as needed and then the appropriate dependencies will get installed alongside it as well.

**Comment by NorwegianRockCat** [comment]
> On 27 Dec 2016, at 17:17, Ken Moore <notifications@github.com> wrote:
> 
> Ok, we just talked about this internally and decided on the following:
> 
> 	• Update the xrdb port to add a runtime dependency on a compiler (the real source of the issue - unlisted runtime dependency within the port).
> 	• Remove xrdb as a dependency of the trueos-base and trueos-desktop packages. TrueOS does not actually use xrdb, and that will keep the default installs smaller and such.
> This should clean things up considerably, because xrdb is getting used less and less as time goes on (TrueOS does not use it at all out-of-box), but it is still available for people to install/use as needed and then the appropriate dependencies will get installed alongside it as well.

Either of those (or actually I guess both) should clear up the issue. I’ve used xrdb to have a good looking and functioning xterm, so I’m glad the runtime dependency was flagged as well.
