### ISSUE TITLE
OpenRC service file request -- nessusd

### ISSUE THREAD

**Issue by VulcanRidr** [trueos/trueos-core#272]
Request an openrc service file Nessus daemon, I am currently running version 6.9.3, if the version matters...Hopefully it doesn't.

**Comment by baitisj** [comment]
Hi VulcanRidr: when I search for `nessus` in the ports tree, I see:
```
Port:	security/nessus
Moved:	
Date:	2016-09-30
Reason:	Has expired: Abandoned, consider using OpenVAS
```

Hence I do not see any port in TrueOS corresponding to `nessus.` Care to point me in the right direction?

**Comment by VulcanRidr** [comment]
I am actually running the current tenable version, 6.9.3. Attached is the
.txz.​
 Nessus-6.9.3-fbsd10-amd64.txz
<https://drive.google.com/file/d/0B58Vtb_JglCJdWp5ODZ2Q1FSemM/view?usp=drive_web>
​

**Comment by baitisj** [comment]
Ah. So you got this from https://www.tenable.com/products/nessus/select-your-operating-system ?

I know this is probably not the answer you want to hear, but it seems like... the vendor should include an openrc script.

I'm pretty sure that supporting this is out of the scope of the TrueOS project, and hence I'll close the bug here. Follow up with the vendor to include an openrc script inside of the official distribution package.

That said, it will probably be VERY easy for you to create a service file. I'm going to attach a very simple example here that should get you started. You can copy it to `/usr/local/etc/init.d/nessus` and modify it.

[rsync.txt](https://github.com/trueos/trueos-core/files/691127/rsync.txt)

**Comment by VulcanRidr** [comment]
Thanks Jeff. You're right that this is probably out of scope for the
project. That said, getting anything like this out of tenable is like
pulling teeth. Hell, at work, I'm a paying customer, and I have been trying
for the last 4 months to get an updated postgresql compliance scan, since
the scan is for postgres 9.1, which was EOL'ed 4 months ago.

So I will give a shot at creating it myself. I just hadn't been able to
find any docs on how it is set up for TrueOS. Do you want the file once I
manage to create it?

Also, the other one that said file not found was netif. Was that deprecated?

Thanks,
--b

**Comment by baitisj** [comment]
If you want to attach the completed script here, that would be cool (you'll need to change the suffix to `.txt`)... maybe someone else will be able to use it.

If you would like a few more examples to look at, try taking a peek inside of `/usr/local/etc/init.d` . All of the scripts that you find in there /should/ be executed by the openrc system.
