### ISSUE TITLE
Unable to open any of the qt based projects in QT Creator

### ISSUE THREAD

**Issue by ghost** [trueos/trueos-core#284]
Hi

This is probably a very basic issue- how do I configure QT Creator so that I can see the UI screens for (eg) Sysadm qt portion and similarly other qt based UI. I am working in Windows 8 / Do I need to work in a Linux os>or is there some other way to solve this?

Yours sincerely,
Arvind.

**Comment by beanpole135** [comment]
While I am a bit unfamiliar with QtCreator (don't use it myself), it should be able to load the *.ui files just fine on Windows.
A couple steps that come to mind:
1) Make sure you have the proper version of QtCreator (Windows 8, Qt5 support)
2) Check out the source tree for the project of interest (SysAdm UI: https://github.com/trueos/sysadm-ui-qt)
3) Start up QtCreator and tell it to load the right *.pro file (SysAdm UI sources: src-qt5/gui_client/gui_client.pro)

If that still does not work for some reason, you can try using the QtDesigner utility instead of QtCreator (standard Qt developer utility). QtDesigner is specifically designed for loading/modifying *.ui files and does not try to be a full IDE like QtCreator, so it tends to work a lot better and it is what I use for developing the Qt utilities in TrueOS.

**Comment by pkgdemon** [comment]
Please let us know if the ui files are not opening as expected, and we will re-open.
