### ISSUE TITLE
SysAdm should offer keyboard-related preferences

### ISSUE THREAD

**Issue by kmoore134** [trueos/trueos-core#78]
_From @grahamperrin on August 9, 2016 9:21_

At least: layouts.

_Copied from original issue: trueos/sysadm#22_

**Comment by beanpole135** [comment]
Not going to happen. Keyboard settings are specific to the system the user is actively using rather than something you want to set on some remote system.

For local-system keyboard settings, we have the Fcitx utility pre-installed on TrueOS desktops now, so that users can quickly perform keyboard layout/locale changes from within a desktop session. If this is something that you need to use on a regular basis, I recommend telling Lumina to automatically start up that utility on login.
