### ISSUE TITLE
net/vnstat

### ISSUE THREAD

**Issue by pkgdemon** [trueos/trueos-core#818]

**Comment by forester9685** [comment]
Hi,

I installed vnstat and try to start it. Getting below message. I share this situation in discourse.trueos.org and experts direct me here. They are suspecting that issue is related to OpenRC. Thanks in advance for your help.

https://discourse.trueos.org/t/vnstat-service-cant-start/1548/3

[uguler@trueos-7861] ~% service vnstat start
 * service: service `vnstat' does not exist
[uguler@trueos-7861] ~%

**Comment by ZackaryWelch** [comment]
OpenRC script created and tested. Should work now. Please let us know if any errors are found.
https://github.com/trueos/freebsd-ports/commit/19ffc884bd3420f38c3b0a211b15faebe4ab1757
